version: '3.8'

services:
  api-gateway:
    build: ./Api-gateway
    ports:
      - "5000:5000"
    env_file: ./Api-gateway/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6380
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    volumes:
      - logs:/app/logs
      - uploads:/app/uploads
    networks:
      - node-microservices

  identity-service:
    build: ./Identity-service
    ports:
      - "5001:5001"
    env_file: ./Identity-service/.env
    depends_on:
      - redis
      - rabbitmq
      - mongoDB
    environment:
      - REDIS_URL=redis://redis:6380
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    volumes:
      - logs:/app/logs
      - uploads:/app/uploads
    networks:
      - node-microservices

  post-service:
    build: ./post-service
    ports:
      - "5002:5002"
    env_file: ./post-service/.env
    depends_on:
      - redis
      - rabbitmq
      - mongoDB
    environment:
      - REDIS_URL=redis://redis:6380
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    volumes:
      - logs:/app/logs
      - uploads:/app/uploads
    networks:
      - node-microservices

  media-service:
    build: ./media-service
    ports:
      - "5003:5003"
    env_file: ./media-service/.env
    depends_on:
      - redis
      - rabbitmq
      - mongoDB
    environment:
      - REDIS_URL=redis://redis:6380
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    volumes:
      - logs:/app/logs
      - uploads:/app/uploads
    networks:
      - node-microservices

  search-service:
    build: ./search-service
    ports:
      - "5004:5004"
    env_file: ./search-service/.env
    depends_on:
      - redis
      - rabbitmq
      - mongoDB
    environment:
      - REDIS_URL=redis://redis:6380
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    volumes:
      - logs:/app/logs
      - uploads:/app/uploads
    networks:
      - node-microservices

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - node-microservices

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq_data:/data
    networks:
      - node-microservices

networks:
  node-microservices:
    driver: bridge

volumes:
  logs:
  uploads:
  redis_data:
  rabbitmq_data: